version: '3.8'

services:
  app:
    build: .
    container_name: order-payment
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
    networks:
      - payment_network

  mysql:
    image: mysql:8.4
    container_name: mysql-payment
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_bd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - payment_network

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    container_name: kakfa-broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kakfa-broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - payment_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: load-balancer
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - payment_network

networks:
  payment_network:
    driver: bridge
